-- Exam Atlas database setup
-- Run this entire file once in Supabase Dashboard → SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.notes (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '',
  question_id text not null default '',
  topics text[] not null default '{}',
  refs text not null default '',
  body text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- These statements also upgrade the original JAM Notes table safely.
alter table public.notes add column if not exists exam text not null default '';
alter table public.notes add column if not exists year integer;
alter table public.notes add column if not exists difficulty text not null default 'medium';
alter table public.notes add column if not exists status text not null default 'understood';
alter table public.notes add column if not exists key_insight text not null default '';
alter table public.notes add column if not exists traps text not null default '';
alter table public.notes add column if not exists formulas text not null default '';
alter table public.notes add column if not exists related_note_ids text[] not null default '{}';
alter table public.notes add column if not exists created_at timestamptz not null default now();
alter table public.notes add column if not exists updated_at timestamptz not null default now();

create table if not exists public.study_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null,
  questions_solved integer not null default 0 check (questions_solved >= 0),
  study_minutes integer not null default 0 check (study_minutes >= 0),
  reflection text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, log_date)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists notes_set_updated_at on public.notes;
create trigger notes_set_updated_at
before update on public.notes
for each row execute function public.set_updated_at();

drop trigger if exists study_logs_set_updated_at on public.study_logs;
create trigger study_logs_set_updated_at
before update on public.study_logs
for each row execute function public.set_updated_at();

create index if not exists notes_user_updated_idx on public.notes (user_id, updated_at desc);
create index if not exists notes_user_created_idx on public.notes (user_id, created_at desc);
create index if not exists notes_topics_gin_idx on public.notes using gin (topics);
create index if not exists study_logs_user_date_idx on public.study_logs (user_id, log_date desc);

alter table public.notes enable row level security;
alter table public.study_logs enable row level security;

-- Remove every earlier policy before installing the definitive private-account
-- rules. PostgreSQL combines permissive policies with OR, so leaving an older
-- broad policy in place could accidentally weaken privacy.
do $$
declare policy_row record;
begin
  for policy_row in
    select policyname from pg_policies where schemaname = 'public' and tablename = 'notes'
  loop
    execute format('drop policy if exists %I on public.notes', policy_row.policyname);
  end loop;
end $$;

create policy "exam_atlas_notes_select_own" on public.notes
for select to authenticated using ((select auth.uid()) = user_id);

create policy "exam_atlas_notes_insert_own" on public.notes
for insert to authenticated with check ((select auth.uid()) = user_id);

create policy "exam_atlas_notes_update_own" on public.notes
for update to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "exam_atlas_notes_delete_own" on public.notes
for delete to authenticated using ((select auth.uid()) = user_id);

do $$
declare policy_row record;
begin
  for policy_row in
    select policyname from pg_policies where schemaname = 'public' and tablename = 'study_logs'
  loop
    execute format('drop policy if exists %I on public.study_logs', policy_row.policyname);
  end loop;
end $$;

create policy "exam_atlas_logs_select_own" on public.study_logs
for select to authenticated using ((select auth.uid()) = user_id);

create policy "exam_atlas_logs_insert_own" on public.study_logs
for insert to authenticated with check ((select auth.uid()) = user_id);

create policy "exam_atlas_logs_update_own" on public.study_logs
for update to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "exam_atlas_logs_delete_own" on public.study_logs
for delete to authenticated using ((select auth.uid()) = user_id);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.notes to authenticated;
grant select, insert, update, delete on public.study_logs to authenticated;
grant usage, select on sequence public.study_logs_id_seq to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.notes;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.study_logs;
exception when duplicate_object then null;
end $$;
